branches:
  main:
    protection:
      required_status_checks:
        strict: true
        contexts: ["validate"]
      required_pull_request_reviews:
        required_approving_review_count: 2
      enforce_admins: true
      restrictions: null

  staging:
    protection:
      required_status_checks:
        strict: true
        contexts: ["validate"]
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
      restrictions: null

  dev:
    protection:
      required_status_checks:
        strict: true
        contexts: ["validate"]
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: false
      restrictions: null