version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    target-branch: "dev"
    # Auto-merge configuration
    auto-merge: true
    auto-merge-conditions:
      - "status-success=test"
      - "status-success=build"
    version-requirement-updates: "increase"

  # Terraform dependencies updates
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "terraform"
      - "dependencies"
    commit-message:
      prefix: "terraform"
      include: "scope" 
    target-branch: "dev"
    # Auto-merge configuration
    auto-merge: true
    auto-merge-conditions:
      - "status-success=test"
      - "status-success=build"
    version-requirement-updates: "increase"