version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Terraform dependencies updates
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"

