name: Application CI Pipeline

on:
  pull_request:
    branches: [ dev, staging, main ]
    paths:
      - 'app/**'
      - '.github/workflows/app-ci.yml'
      - 'package*.json'
      - 'Dockerfile'
      - '!infra/**'  # Exclude infra changes

permissions:
  id-token: write
  contents: read

jobs:
  security-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app  # Set the working directory to app folder
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
          
      - name: Install dependencies
        run: |
          npm install
          npm ci
        
      - name: Run npm audit
        run: |
          npm audit --json > npm-audit-report.json || true
          npm audit fix --audit-level=critical --force
          if [ $(jq '.vulnerabilities | length' npm-audit-report.json) -gt 0 ]; then
            echo "Critical vulnerabilities found:"
            jq '.vulnerabilities[] | select(.severity=="critical")' npm-audit-report.json
            exit 1
          fi
        
      - name: Run Tests with Coverage
        run: |
          npm run test:coverage
        
      - name: Run SAST with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: app
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/coverage/**,**/public/**
            -Dsonar.coverage.exclusions=**/public/**
            -Dsonar.verbose=true
        
      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=app/package.json
          
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'portfolio-app'
          path: '.'
          format: 'HTML'
          
      - name: Run Integration Tests
        run: npm run test:integration

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            app/npm-audit-report.json
            app/dependency-check-report.html
            app/coverage/**
            trivy-results.sarif

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: eu-west-1
          
      - name: Upload Reports to S3
        run: |
          REPORT_DIR="reports/${{ github.repository }}/${{ github.ref_name }}/${{ github.sha }}"
          
          # Create reports directory if it doesn't exist
          mkdir -p reports
          
          # Copy all reports to a single directory
          cp app/npm-audit-report.json reports/ || true
          cp app/dependency-check-report.html reports/ || true
          cp -r app/coverage reports/ || true
          cp trivy-results.sarif reports/ || true
          
          # Upload all reports to S3
          aws s3 cp reports/. "s3://${{ secrets.REPORTS_BUCKET }}/$REPORT_DIR/" --recursive
          
          # Generate and upload report index
          echo "Security Reports for ${{ github.repository }} - ${{ github.sha }}" > reports/index.html
          echo "Generated on $(date)" >> reports/index.html
          echo "<ul>" >> reports/index.html
          echo "<li><a href='npm-audit-report.json'>NPM Audit Report</a></li>" >> reports/index.html
          echo "<li><a href='dependency-check-report.html'>OWASP Dependency Check Report</a></li>" >> reports/index.html
          echo "<li><a href='coverage/lcov-report/index.html'>Test Coverage Report</a></li>" >> reports/index.html
          echo "<li><a href='trivy-results.sarif'>Trivy Scan Results</a></li>" >> reports/index.html
          echo "</ul>" >> reports/index.html
          
          aws s3 cp reports/index.html "s3://${{ secrets.REPORTS_BUCKET }}/$REPORT_DIR/index.html"

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: |
            Security Scan for PR #${{ github.event.pull_request.number }} ${{ job.status }}!
            Branch: ${{ github.head_ref }}
            Reports: s3://${{ secrets.REPORTS_BUCKET }}/${{ github.repository }}/${{ github.ref_name }}/${{ github.sha }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


