name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      confirm_destroy:
        description: 'Type DESTROY to confirm infrastructure destruction'
        required: true
        type: string

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    defaults:
      run:
        working-directory: ./infra
    
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        aws-region: eu-west-1
        role-session-name: GitHubActions

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Select Workspace
      run: terraform workspace select ${{ github.event.inputs.environment }}

    - name: Terraform Destroy
      run: |
        terraform destroy \
          -var-file="environments/terraform.tfvars.${{ github.event.inputs.environment }}" \
          -auto-approve

    - name: Notify Slack on Destruction
      uses: slackapi/slack-github-action@v1.24.0
      if: always()
      with:
        channel-id: 'infrastructure'
        slack-message: |
          Infrastructure Destruction Status: ${{ job.status }}
          Environment: ${{ github.event.inputs.environment }}
          Triggered by: ${{ github.actor }}
          Workflow: ${{ github.workflow }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 